### ISSUE TITLE
Report definition description rich text

### ISSUE THREAD

**Issue by ThomasVermes** [Nottingham-CTU/Advanced-Reports#17]
Hello,
first of all, thank you very much for this great module.
I would really like to have html tags or richt text enable in the Report definition description in order to provide some user friendly (with nice layout) explanation to the end user.
That's my suggestion =)

**Comment by richdooley** [comment]
HTML `<b>` and `<i>` tags are now supported in report descriptions (in addition to `<a>` link tags).
