### ISSUE TITLE
Error: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by 274188A** [Nottingham-CTU/Advanced-Reports#22]
v1.4.0
REDCap 13.10.0 · PHP 8.2.7 (Windows OS) · MySQL 8.0.34

>Error message: Uncaught TypeError: Cannot access offset of type string on string in modules\ae_reporting_v1.2\pages\classes\common.php:186 Stack trace: #0 modules\ae_reporting_v1.2\pages\mapping.php(237): HarvardCatalystPartnersHealthCare\AEreporting\access_event_names_xproject(NULL) #1 redcap_v13.10.0\ExternalModules\index.php(146): require('...') #2 {main} thrownFile: modules\ae_reporting_v1.2\pages\classes\common.phpLine: 186

**Comment by richdooley** [comment]
This doesn't appear to relate to this module.
