### ISSUE TITLE
Add aggregate function: Count

### ISSUE THREAD

**Issue by jgardner-qha** [Nottingham-CTU/Advanced-Reports#26]
Thanks for your work on this module, I really like it.

I would really like to see Count added to the grouping functions on the Instrument Query report. I dabbled with the code and was able to make it work, but it's probably not up to coding standards (I'm no developer).

**Comment by richdooley** [comment]
Count can be performed by selecting *sum* of `1`.
See the [instrument query wiki page](https://github.com/Nottingham-CTU/Advanced-Reports/wiki/Instrument-Query) for an example.

**Comment by jgardner-qha** [comment]
That'll work perfectly, thank you @richdooley!
