### ISSUE TITLE
Add DAG Filter

### ISSUE THREAD

**Issue by jgardner-qha** [Nottingham-CTU/Advanced-Reports#27]
Would it be possible to add an option to filter a given report to the user's DAG?

Perhaps, for example, add a checkbox to the Instrument Query Report edit screen that, if checked, the displayed report would be automatically filtered by the viewer's assigned DAG, or not filtered if the user is not assigned to a DAG.

Let me know if you have questions.

**Comment by richdooley** [comment]
An example of filtering by user's assigned DAG has been added to the  [instrument query wiki page](https://github.com/Nottingham-CTU/Advanced-Reports/wiki/Instrument-Query).
