### ISSUE TITLE
Inclusion of descriptive field types in Instrument Query report

### ISSUE THREAD

**Issue by JamesPBrown** [Nottingham-CTU/Advanced-Reports#29]
Hi

I've been using AR for a while (it's a game changer!) but predominately SQ report (the presentation you and Nick did a while ago was great). Starting to look to use Instrument Query and noticed the descriptive fields appear not be be excluded for the report as I would have expected. I cannot think of a reason too included them (but that of course doesn't mean there isn't one).

**Comment by richdooley** [comment]
This was fixed in version 1.5.0.
